### ISSUE TITLE
Beta.6  opening sharing links generates errors ,contain maps in Display

### ISSUE THREAD

**Issue by Lee-Lane** [edp963/davinci#1076]
When sharing Widgets that contain maps in Display, opening sharing links generates errors.

`vendor.b3714924781d0b607281.chunk.js:1 
TypeError: Cannot read property 'visualType' of undefined
    at app~share.0fe8edb3568412ab4fb3.chunk.js:1
    at Array.filter (<anonymous>)
    at ua (app~share.0fe8edb3568412ab4fb3.chunk.js:1)
    at Ca (app~share.0fe8edb3568412ab4fb3.chunk.js:1)
    at t.n.renderChart (app~share.0fe8edb3568412ab4fb3.chunk.js:1)
    at t.value (app~share.0fe8edb3568412ab4fb3.chunk.js:1)
    at Eo (vendor.b3714924781d0b607281.chunk.js:1)
    at Oo (vendor.b3714924781d0b607281.chunk.js:1)
    at Co (vendor.b3714924781d0b607281.chunk.js:1)
    at ko (vendor.b3714924781d0b607281.chunk.js:1)
bi @ vendor.b3714924781d0b607281.chunk.js:1
vendor.b3714924781d0b607281.chunk.js:1 
uncaught at yt TypeError: Cannot read property 'visualType' of undefined
    at http://192.168.200.114:8080/app~share.0fe8edb3568412ab4fb3.chunk.js:1:440432
    at Array.filter (<anonymous>)
    at ua (http://192.168.200.114:8080/app~share.0fe8edb3568412ab4fb3.chunk.js:1:440385)
    at Ca (http://192.168.200.114:8080/app~share.0fe8edb3568412ab4fb3.chunk.js:1:460091)
    at t.n.renderChart (http://192.168.200.114:8080/app~share.0fe8edb3568412ab4fb3.chunk.js:1:466060)
    at t.value (http://192.168.200.114:8080/app~share.0fe8edb3568412ab4fb3.chunk.js:1:467278)
    at Eo (http://192.168.200.114:8080/vendor.b3714924781d0b607281.chunk.js:1:1301990)
    at Oo (http://192.168.200.114:8080/vendor.b3714924781d0b607281.chunk.js:1:1297359)
    at Co (http://192.168.200.114:8080/vendor.b3714924781d0b607281.chunk.js:1:1296860)
    at ko (http://192.168.200.114:8080/vendor.b3714924781d0b607281.chunk.js:1:1295939)
D @ vendor.b3714924781d0b607281.chunk.js:1
share.9c5bac35e7ada0db2d5f.chunk.js:1
 share page need login...
Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by GZ315200** [comment]
This is a BUG, I have already fixed it.

**Comment by AndyFong** [comment]
fixed
