### ISSUE TITLE
Can not schedule screenshot image on windows.

### ISSUE THREAD

**Issue by mingchau** [edp963/davinci#1238]
The whole application runs as expected on my windows 10 pc except the schedule of sending images, which raise error:
> java.lang.IllegalStateException: The driver executable does not exist: D:\davinci-assembly_3.0.1\bin\$your_phantomjs_path$
2019-09-20 16:20:00.099  INFO 14148 --- [pool-3-thread-2] e.d.service.screenshot.ScreenshotUtil    : thread for screenshot finish, type: portal, id: 1
        at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
        at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:136)
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.findPhantomJS(PhantomJSDriverService.java:245)
        at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:181)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:105)
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:95)
        at edp.davinci.service.screenshot.ScreenshotUtil.generatePhantomJsDriver(ScreenshotUtil.java:196)
        at edp.davinci.service.screenshot.ScreenshotUtil.generateWebDriver(ScreenshotUtil.java:150)
        at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:105)
        at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:75)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

I have already added the system environment variable: 
>phantomjs_home=D:\phantomjs-2.1.1-windows\bin\phantomjs.exe 

Thanks for your help!

**Comment by mingchau** [comment]
Need to specify the 
>phantomjs_path: D:\phantomjs-2.1.1-windows\bin\phantomjs.exe
in application.yml
