### ISSUE TITLE
davinci-0.3.0-beta.7  connect elasticsearch V5.3.2  error

### ISSUE THREAD

**Issue by hapuer** [edp963/davinci#1241]
Caused by: java.lang.NoSuchFieldError: connectionIdSeed

**Comment by xujiexin** [comment]
相同的错误，我也遇到了，还没解决，你有解决吗
Caused by: java.lang.NoSuchFieldError: connectionIdSeed
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.init(ElasticSearchDruidDataSource.java:487)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:897)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:893)
	at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:57)
	at edp.core.utils.SourceUtils.getConnection(SourceUtils.java:77)
	at edp.core.utils.SqlUtils.testConnection(SqlUtils.java:670)
	at edp.davinci.service.impl.SourceServiceImpl.testSource(SourceServiceImpl.java:337)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
	at com.sun.proxy.$Proxy149.testSource(Unknown Source)

**Comment by hapuer** [comment]
没有解决，我看了代码，他们代码有问题

发自我的 iPhone

**Comment by RichardShan** [comment]
The driver from [NLPchina elasticsearch-sql](https://github.com/NLPchina/elasticsearch-sql)  depends on [druid](https://github.com/alibaba/druid), which  [version is 1.1.11](https://github.com/alibaba/druid/releases/tag/1.1.11) in Davinci , this exception is due to druid version confliction, so you can connect elasticsearch by [the way of multi-version isolation](https://github.com/edp963/davinci/releases/tag/v0.3.0-beta.7).

**Comment by JiangPW** [comment]
@RichardShan 通过多版本隔离的方式连接elasticsearch同样存在这样的问题，不知道多版本隔离方式是否有误？
使用的elasticsearch版本是7.3.1，从NLPchina elasticsearch-sql获取相应版本驱动elasticsearch-sql-7.3.1.0.jar，对应的druid版本是druid-1.1.16.jar。
datasource_driver.yml配置如下：
```
elasticsearch7.3.1:
   name: elasticsearch2
   desc: elasticsearch
   version: 7.3.1
   driver: org.elasticsearch.plugin.nlpcn.SqlPlug
   keyword_prefix: \`
   keyword_suffix: \`
   alias_prefix: \'
   alias_suffix: \'
```
按照文档说明在lib目录创建/ext/elasticsearch2/7.3.1，并将驱动jar放于此目录
```
druid-1.1.16.jar
elasticsearch-7.3.1.jar
elasticsearch-sql-7.3.1.0.jar
transport-7.3.1.jar
x-pack-api-6.0.0-alpha2.jar
x-pack-transport-6.0.0-alpha2.jar
```
重启davinci依旧出现此方式，除此还尝试了将lib下druid-1.1.11.jar替换成druid-1.1.16.jar。问题依旧

**Comment by quietStrength** [comment]
> 没有解决，我看了代码，他们代码有问题 发自我的 iPhone
> […](#)
> 在 2019年9月23日，下午4:18，xujiexin ***@***.***> 写道： 相同的错误，我也遇到了，还没解决，你有解决吗 Caused by: java.lang.NoSuchFieldError: connectionIdSeed at com.alibaba.druid.pool.ElasticSearchDruidDataSource.init(ElasticSearchDruidDataSource.java:487) at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:897) at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:893) at com.alibaba.druid.pool.ElasticSearchDruidDataSource.getConnection(ElasticSearchDruidDataSource.java:57) at edp.core.utils.SourceUtils.getConnection(SourceUtils.java:77) at edp.core.utils.SqlUtils.testConnection(SqlUtils.java:670) at edp.davinci.service.impl.SourceServiceImpl.testSource(SourceServiceImpl.java:337) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206) at com.sun.proxy.$Proxy149.testSource(Unknown Source) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

hello,用的es6.3.2版本，遇到了同样的问题，问下这个问题目前有解决吗？感谢

**Comment by admin1strat0r** [comment]
ES6.6.2版本遇到同样的问题，然后采用x-pack-sql-jdbc-6.6.2的方式进行连接，DEMO是可以正常的增删改查，但是继承到Davinci里面就有问题了，有没有大牛解决的，交流一下，非常感谢。

**Comment by quietStrength** [comment]
看了druid的1.1.16版本 protected volatile long connectionIdSeed;   这个属性仍然是long类型，代码引用时候却还   this.connectionIdSeed.addAndGet(delta);这样调用。。困惑。到底用哪个版本的Druid？

**Comment by quietStrength** [comment]
> 看了druid的1.1.16版本 protected volatile long connectionIdSeed; 这个属性仍然是long类型，代码引用时候却还 this.connectionIdSeed.addAndGet(delta);这样调用。。困惑。到底用哪个版本的Druid？

解决 用的1.0X的版本druid。。。。囧

**Comment by quietStrength** [comment]
> The driver from [NLPchina elasticsearch-sql](https://github.com/NLPchina/elasticsearch-sql) depends on [druid](https://github.com/alibaba/druid), which [version is 1.1.11](https://github.com/alibaba/druid/releases/tag/1.1.11) in Davinci , this exception is due to druid version confliction, so you can connect elasticsearch by [the way of multi-version isolation](https://github.com/edp963/davinci/releases/tag/v0.3.0-beta.7).

hello，want to ask a question : the way of multi-version isolation is not userfull for elasticsearch？I have configed as user document said,but jars in ext/es/6.3.0 have no effect...thanks very much
