### ISSUE TITLE
Which driver mongodb needs to add?

### ISSUE THREAD

**Issue by anmofree** [edp963/davinci#1288]
I added the mongo-java-driver-3.0.1.jar to ./lib.

error:
    Not supported data type: jdbcUrl=jdbc:mongodb://xxxxxxxxxx:27017/xxxx

Who can help solve this problem???

thanks!!!

**Comment by AndyFong** [comment]
https://edp963.github.io/davinci/deployment.html#3-%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AE

**Comment by anmofree** [comment]
This document cann't solved this problem!
Can you provide the specific driver package name???

**Comment by AndyFong** [comment]
Please follow the tutorial instructions, you must have not updated the `datasource_driver.yaml` file.

**Comment by anmofree** [comment]
This document cann't solved this problem!
Can you provide the specific driver package name???

**Comment by anmofree** [comment]
Hi,
I did the following, but it still didn't work.

1、I added the mongo-java-driver-3.0.1.jar to ./lib .
2、I added the following to the datasource_driver.yml
      mongodb:
           name: mongodb
           desc: mongodb
           version:
           driver: mongodb.jdbc.MongoDriver

error:

2019-10-31 19:52:25.397  INFO 11907 --- [main] org.mongodb.driver.cluster               : Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
n(DefaultServerMonitor.java:128)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50)
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58)
        ... 3 common frames omitted

      Not supported data type: jdbcUrl=jdbc:mongodb://xxxxxxxxxx:27017/xxxx

**Comment by RichardShan** [comment]
It's a bug, we will fix it in next release
