### ISSUE TITLE
Integrated ldap error [LDAP: error code 34 - invalid DN]

### ISSUE THREAD

**Issue by BBenQi** [edp963/davinci#1307]
the error: 
`org.springframework.ldap.InvalidNameException: [LDAP: error code 34 - invalid DN]; nested exception is javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
	at org.springframework.ldap.support.LdapUtils.convertLdapException(LdapUtils.java:136)
	at org.springframework.ldap.core.support.AbstractContextSource.createContext(AbstractContextSource.java:355)
	at org.springframework.ldap.core.support.AbstractContextSource.doGetContext(AbstractContextSource.java:139)
	at org.springframework.ldap.core.support.AbstractContextSource.getContext(AbstractContextSource.java:130)`

and my config:

-   ldap:
    urls: ldap://smark.com:389
    username: cn=admin,dc=smark,dc=com
    password: 123456a?
    base: ou=inspur,dc=smark,dc=com
    domainName: '@smark.com'

**Comment by xianhongzou** [comment]
I also encounter this problem,expect the answer earlier

**Comment by xianhongzou** [comment]
I had solved this problem by change the code in LdapServiceImpl.java，it because of the ldap DN changed the username+domainName,so ldap server invalid the DN

**Comment by stalary** [comment]
I have the same problem

**Comment by GustavoBPaulus** [comment]
I am with the same problem, how can I solve it?

**Comment by xxxuexx** [comment]
> I had solved this problem by change the code in LdapServiceImpl.java，it because of the ldap DN changed the username+domainName,so ldap server invalid the DN

请问修改完 LdapServiceImpl.java后 mvn clean package 后运行./start-server.sh启动报错，错误: 找不到或无法加载主类 edp.DavinciServerApplication
