### ISSUE TITLE
No Mail attachment with picture

### ISSUE THREAD

**Issue by Jaltte** [edp963/davinci#1356]
I pick picture format Email.It's all OK in my local windows environment.But When it is deployed to the linux server，I can't see the picture attachment in my email.
Excel format is OK...

**Comment by AndyFong** [comment]
*ref:*  
https://edp963.github.io/davinci/docs/zh/1.1-deployment#244-%E6%88%AA%E5%9B%BE%E9%85%8D%E7%BD%AE

**Comment by Jaltte** [comment]
> _ref:_
> https://edp963.github.io/davinci/docs/zh/1.1-deployment#244-%E6%88%AA%E5%9B%BE%E9%85%8D%E7%BD%AE

Following the doc,problem still exist!I got the error message:

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for at least one condition to be valid: presence of element located by: By.id: headlessBrowserRenderSign || presence of element located by: By.id: width || presence of element located by: By.id: height (tried for 600 second(s) with 500 MILLISECONDS interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at aii.aboard.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:98)
	at aii.aboard.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: height
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'Web02', ip: '10.21.35.112', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.10.1.el7.x86_64', java.version: '1.8.0_162'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1427)
	at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1421)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
	... 7 common frames omitted

**Comment by Jaltte** [comment]
@AndyFong @MountHuang This is weird,I have never encountered this kind of error.Please help me.

**Comment by hornsey** [comment]
you can check two things in server  :1、 LANG env ；2、the fonts you need. Help it can help you.
