### ISSUE TITLE
无法定时发送邮件

### ISSUE THREAD

**Issue by wangjingxiangg** [edp963/davinci#1386]
2019-12-13 17:10:01.577  INFO 121405 --- [pool-5-thread-2] e.d.service.screenshot.ScreenshotUtil    : finish screenshot for job: 4
java.lang.IllegalArgumentException: File must not be null
	at org.springframework.util.Assert.notNull(Assert.java:193)
	at org.springframework.mail.javamail.MimeMessageHelper.addInline(MimeMessageHelper.java:912)
	at edp.core.utils.MailUtils.lambda$sendMail$1(MailUtils.java:185)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at edp.core.utils.MailUtils.sendMail(MailUtils.java:182)
	at edp.davinci.service.impl.EmailScheduleServiceImpl.execute(EmailScheduleServiceImpl.java:191)
	at edp.core.common.quartz.QuartzJobExecutor.lambda$execute$0(QuartzJobExecutor.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-12-13 17:10:01.580 ERROR 121405 --- [pool-5-thread-2] e.core.common.quartz.QuartzJobExecutor   : File must not be null
2019-12-13 17:12:01.331  INFO 121405 --- [pool-3-thread-4] e.d.service.screenshot.ScreenshotUtil    : finish get http://localhost:8080/share.html#/share/display?shareInfo=DA1C3E7DAF7EC46FDC39861F361C78B7517FC6CEF4F1ED425FFF75A2CB7527D3ABD4F0725AF12462EE9485E57D523401312C48BC4BC5B69AD940692B1F2E55F358A03947A8456C542968B4C4D572B6F9B7F447349327E9309C2587C6BFA979361456B5FBCAF282D3E95BEF815198FB040D7BAD6F5AA490947F4F1BAADCF26EF599A61F03801710C5C8947648890D7B5705C6A3BE3B6338AFABFFA4884F6358EF485523DCAD55902B6CF0DE309F72C8FABF7248C4F1B9338D6DC80B1E9AF9D64A65C1F83B44737E708275ED795385A7044EFA47667479E54F1FEE02B845A05974B096600633E9A923E5B70AFECEEDEE77B908E7554754521126C6AC357BCD4A7A, webdriver will quit soon
[INFO  - 2019-12-13T09:12:01.379Z] ShutdownReqHand - _handle - About to shutdown
2019-12-13 17:12:01.470 ERROR 121405 --- [pool-3-thread-4] e.d.service.screenshot.ScreenshotUtil    : error ScreenshotUtil.screenshot, 

org.openqa.selenium.TimeoutException: Expected condition failed: waiting for at least one condition to be valid: presence of element located by: By.id: headlessBrowserRenderSign || presence of element located by: By.id: width || presence of element located by: By.id: height (tried for 600 second(s) with 500 MILLISECONDS interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
	at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:115)
	at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:75)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: Cannot locate an element using By.id: height
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'localhost.localdomain', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.el7.x86_64', java.version: '1.8.0_191'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)

**Comment by scottsut** [comment]
Please post your `server` and `screenshot` configurations in `application.yml`
