### ISSUE TITLE
we can't add the datasource for kylin

### ISSUE THREAD

**Issue by zzm9201989** [edp963/davinci#1474]
1. we copy the kylin jdbc driver to lib dir 
[root@cdh-3 lib]# ls -trlh *kylin*
-rw-r--r-- 1 root root 5.5M Feb  7 16:12 kylin-jdbc-3.0.0.jar
-rwxr-xr-x 1 root root 5.4M Feb  7 16:20 kylin-jdbc-2.6.1.jar
-rwxr-xr-x 1 root root 5.2M Feb 11 17:04 kylin-jdbc-2.3.0.jar
2. 'Internal Server Error ' returned  when we add the kylin datasource ：
![image](https://user-images.githubusercontent.com/46475593/74298497-ee76b400-4d84-11ea-8f80-0049df15f005.png)
3. the log  ‘java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver’ disappeared
4. how to add the kylin datasource?
error-log.txt

**Comment by zzm9201989** [comment]
2020-02-12 10:55:05.255 ERROR 74717 --- [2-18080-exec-10] e.d.core.config.RestExceptionHandler     : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver
2020-02-12 10:55:05.255 ERROR 74717 --- [http-nio-10.10.16.12-18080-exec-10] e.d.core.config.RestExceptionHandler     : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver
spatcherServlet.java:1006)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at edp.core.utils.SourceUtils.checkDriver(SourceUtils.java:160)
        at edp.core.utils.SqlUtils$SqlUtilsBuilder.build(SqlUtils.java:969)
        at edp.core.utils.SqlUtils.init(SqlUtils.java:116)
        at edp.core.utils.SqlUtils$$FastClassBySpringCGLIB$$33c0f0b2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
        at edp.core.utils.SqlUtils$$EnhancerBySpringCGLIB$$a2b012b0.init(<generated>)
        at edp.davinci.service.impl.SourceServiceImpl.testSource(SourceServiceImpl.java:337)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
        at com.sun.proxy.$Proxy142.testSource(Unknown Source)
        at edp.davinci.controller.SourceController.testSource(SourceController.java:210)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        ... 34 more
2020-02-12 10:55:22.052 ERROR 74717 --- [12-18080-exec-5] e.d.core.config.RestExceptionHandler     : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver
2020-02-12 10:55:22.052 ERROR 74717 --- [http-nio-10.10.16.12-18080-exec-5] e.d.core.config.RestExceptionHandler     : Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.kylin.jdbc.Driver

**Comment by RichardShan** [comment]
Multiple versions can cause conflicts, just  leave one of them.
