### ISSUE TITLE
Load "date type" field base SQLserver  have a inside error

### ISSUE THREAD

**Issue by basis100** [edp963/davinci#1544]
Dear all：

I have a table in SQLserver and the table have a  "date type" field, when I was set VIEW in Davinci,
the server have been a a inside error.   

then, if not load the  "date type" field, every thing is OK.  

the Davinci's VIEW is not load "date type" field base  SQLserver ?

thanks a lots.....

**Comment by RichardShan** [comment]
What is the type of this column?  can you provide the server exception log?

**Comment by basis100** [comment]
thanks, the server's log file:

[davinci-error.log](https://github.com/edp963/davinci/files/4311007/davinci-error.log)


2020-03-10 08:04:08.360  INFO 20141 --- [http-nio-127.0.0.1-81-exec-9] com.alibaba.druid.pool.DruidDataSource   : {dataSource-2} inited
.serializer.MapSerializer.write(MapSerializer.java:270)
 at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
 at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:333)
 at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:311)
 at com.alibaba.fastjson.serializer.ASMSerializer_6_PaginateWithQueryColumns.writeNormal(Unknown Source)
 at com.alibaba.fastjson.serializer.ASMSerializer_6_PaginateWithQueryColumns.write(Unknown Source)
 at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:270)
 at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
 at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
 at com.alibaba.fastjson.JSON.writeJSONString(JSON.java:937)
 at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.writeInternal(FastJsonHttpMessageConverter.java:312)
 at org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:226)
 at com.alibaba.fastjson.support.spring.FastJsonHttpMessageConverter.write(FastJsonHttpMessageConverter.java:244)
 at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:272)
 at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:224)
 at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:82)
 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:119)
 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHa

**Comment by basis100** [comment]
![image](https://user-images.githubusercontent.com/26346549/76292183-b2823080-62e9-11ea-8132-2c6e0f7107af.png)
the table have a column is data type.  then, if select the column will been have a inside error.

**Comment by jimxue** [comment]
The DB version SQL SERVER 2017 and JDBC version mssql-jdbc-8.2.1.jre8.jar .

When I create a view with SQL(SELECT mdate FROM BUS_OPR) which include the date column, An error has occured on this page(Internal server error) and the server log is the same with davinci-error.log provided by basis100  ,But When I create view with SQL (SELECT idFROM BUS_OPR) which not include the date column ,it is ok.

**Comment by forrestlmj** [comment]
Same problem with mysql.

**Comment by gs19931024** [comment]
Same problem with mysql in date type
