### ISSUE TITLE
Display辅助图形矩形框设置背景时不成功

### ISSUE THREAD

**Issue by mstaryi** [edp963/davinci#1592]
Display辅助图形矩形框设置背景时不成功
![image](https://user-images.githubusercontent.com/26699467/77400529-4b36a700-6de6-11ea-9440-d5ccdd356cb6.png)

后台错误日志
edp.core.exception.ServerException: display slide widget is not found
        at edp.davinci.service.impl.DisplaySlideServiceImpl.getMemDisplaySlideWidget(DisplaySlideServiceImpl.java:466)
        at edp.davinci.service.impl.DisplaySlideServiceImpl.uploadSlideSubWidgetBGImage(DisplaySlideServiceImpl.java:753)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by scottsut** [comment]
[Release package](https://github.com/edp963/davinci/releases/tag/v0.3.0-beta.9) has been updated, download and redeploy can solve.

**Comment by ghostman-git** [comment]
@scottsut  docker下部署的v0.3.0-beta.9还是有这个问题。

**Comment by scottsut** [comment]
Next release will be resolved.
