### ISSUE TITLE
在 Windows 10 下编译打包的出错

### ISSUE THREAD

**Issue by qiulin** [edp963/davinci#1756]
环境：

Windows 10 / AdoptOpenJDK 8 

问题：

1. npm 安装 webapp 依赖包报错，几个图片处理相关的库安装失败
2. maven 打包运行正常，但在 IDEA 里面直接运行 Application 报错：

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.hibernate.validator.internal.engine.valueextraction.ValueExtractorManager
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:140)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:364)
	at org.springframework.validation.beanvalidation.LocalValidatorFactoryBean.afterPropertiesSet(LocalValidatorFactoryBean.java:309)
	at org.springframework.validation.beanvalidation.OptionalValidatorFactoryBean.afterPropertiesSet(OptionalValidatorFactoryBean.java:40)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
	... 40 common frames omitted
```

**Comment by AndyFong** [comment]
1. ref: #1770 
2. @xxxllluuu

**Comment by lisihong8** [comment]
mine too,too manny bug
