### ISSUE TITLE
npm i  has error

### ISSUE THREAD

**Issue by ittce** [edp963/davinci#1825]
i use cnpm to install  package。
then I get
```zsh
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/qitmac001084/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gypmake: *** [Release/obj.target/fse/fsevents.o] Error 1
 ERR! System Darwin 19.0.0
gyp ERR! command "/Users/qitmac001084/.nvm/versions/node/v10.21.0/bin/node" "/Users/qitmac001084/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gypgyp ERR! cwd /Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
 ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/qitmac001084/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/qitmac001084/.nvm/versions/node/v10.21.0/bin/node" "/Users/qitmac001084/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/qitmac001084/.nvm/versions/node/v10.21.0/bin/node /Users/qitmac001084/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.0.0
node-pre-gyp ERR! command "/Users/qitmac001084/.nvm/versions/node/v10.21.0/bin/node" "/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents
node-pre-gyp ERR! node -v v10.21.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute '/Users/qitmac001084/.nvm/versions/node/v10.21.0/bin/node /Users/qitmac001084/.nvm/versions/node/v10.21.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/qitmac001084/workspace/davinci_node/webapp/node_modules/quill-image-resize-module/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

> pre-commit@1.2.2 install /Users/qitmac001084/workspace/davinci_node/webapp/node_modules/pre-commit
> node install.js

```

**Comment by ittce** [comment]
算了。 自己解决吧。假模假式的要求英文。
感谢开源~。 就酱
