### ISSUE TITLE
image could not send

### ISSUE THREAD

**Issue by ldboyghg** [edp963/davinci#1830]
In schedule task list ,when  task only contain excel, email could send correctly.

but when i attach screenshot image , background dispaly the error like this:

2020-07-01 09:43:05.065  INFO 3095 --- [pool-3-thread-2] e.d.service.screenshot.ScreenshotUtil    : finish get http://localhost:8080/share.html#/share/dashboard?shareInfo=DA1C3E7DAF7EC46FDC39861F361C78B7517FC6CEF4F1ED425FFF75A2CB7527D3ABD4F0725AF12462EE9485E57D523401E5F879A553532AD0E6CC68AC6CA7C9ACE28257B923943DF7C8611C13297832D70E95E750748E56009E7E8369EBF587FFB2A61355A235625968FC7D51AA20A6E94AF282DFB939E9F50F22774DD0B5169743419A59BADDBEF1AF47E27705A851E0B396D290FFF904D45454C7BD342C3E9C750D304C75F499A5A4B8692B41728CBFF3F670DD3225A0D63EBEA603113EDDF202BCE5B3F1584211CE0A85F2809308BF088C294DACE2270CAA4C597F4AA3B5CF8ABF313C67A58CC1ECD038FD5EAD665E736A20B6163E3C8FD42485B35697C256&type=dashboard, webdriver will quit soon
2020-07-01 09:43:05.085 ERROR 3095 --- [pool-3-thread-4] e.d.service.screenshot.ScreenshotUtil    : error ScreenshotUtil.screenshot, 

edp.core.exception.ServerException: Screenshot TIMEOUT: get data time more than: 3600 ms
	at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:136)
	at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-07-01 09:43:05.086  INFO 3095 --- [pool-3-thread-4] e.d.service.screenshot.ScreenshotUtil    : thread for screenshot finish, type: dashboard, id: 30
2020-07-01 09:43:05.103 ERROR 3095 --- [pool-3-thread-1] e.d.service.screenshot.ScreenshotUtil    : error ScreenshotUtil.screenshot
....
....
2020-07-01 09:43:10.316 ERROR 3095 --- [pool-5-thread-1] e.core.common.quartz.QuartzJobExecutor   : File must not be null

---end

I think , the screenshot i config exectly , no problem.
look the error info , my screenshot like exectly running .
but when send the image email , then file name is null !!  couldn't find the file ???

where is my fault?  please help!~~~~~~~~

**Comment by scottsut** [comment]
You can check whether **your server itself** can access http://localhost:8080/.

**Comment by wansoho** [comment]
me too，help me.
