### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by yuanbwhub** [edp963/davinci#1891]
When I use start-server.sh

`Exception in thread "main" java.lang.UnsupportedClassVersionError: akka/actor/ActorRefFactory : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at edp.davinci.DavinciStarter.main(DavinciStarter.scala)

`

**Comment by yuanbwhub** [comment]
thank you so much

**Comment by scottsut** [comment]
https://stackoverflow.com/questions/7237536/exception-in-thread-main-java-lang-unsupportedclassversionerror-a-unsupporte
https://hive.blog/waves/@cryptohead/re-marcjansen-installation-of-a-waves-testnet-node-20160820t013154369z

FYI.
