### ISSUE TITLE
TDengine database: Cannot connect to TDengine after restarting the jar package.

### ISSUE THREAD

**Issue by teacherZF** [edp963/davinci#1979]
**I imported the jar package of TDengine to the lib directory and I still cannot connect to the database after restarting. The error is as follows:**
`2020-10-23 10:25:57.505 ERROR 59504 --- [http-nio-172.31.72.189-8081-exec-4] e.d.service.impl.SourceServiceImpl       : Not supported data type: jdbcUrl=jdbc:TAOS://172.31.68.193:6041/testdb?user=root&password=taosdata
)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
        at com.sun.proxy.$Proxy144.testSource(Unknown Source)
        at edp.davinci.controller.SourceController.testSource(SourceController.java:230)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
2020-10-23 10:25:57.510 ERROR 59504 --- [189-8081-exec-4] e.d.core.config.RestExceptionHandler     : Not supported data type: jdbcUrl=jdbc:TAOS://172.31.68.193:6041/testdb?user=root&password=taosdata
2020-10-23 10:25:57.510 ERROR 59504 --- [http-nio-172.31.72.189-8081-exec-4] e.d.core.config.RestExceptionHandler     : Not supported data type: jdbcUrl=jdbc:TAOS://172.31.68.193:6041/testdb?user=root&password=taosdata`

**How can i solve this problem？**

**Comment by scottsut** [comment]
https://edp963.github.io/davinci/docs/zh/1.1-deployment#31-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90

**Comment by teacherZF** [comment]
@scottsut 
### Can you give me an example of database configuration that is not on the description? Thank you！

**Comment by scottsut** [comment]
```yml
hive2.1.1:
  name: hive2
  desc: hive
  version: 
  driver: org.apache.hive.jdbc.HiveDriver
  keyword_prefix: \`
  keyword_suffix: \`
  alias_prefix: \`
  alias_suffix: \`
```

**Comment by teacherZF** [comment]
@scottsut 
hello , 
TDengine is a new time series database, its JDBC URL is as follows: jdbc:TAOS://172.31.68.193:6041/testdb?user=root&password=taosdata
I configured hive2 according to your method and it was successful, but I configured TDengine and still reported the above error. This is my configuration:
  ```
TDengine:
    name: TAOS
    desc: TAOS
    version:
    driver: com.taosdata.jdbc.TSDBDriver
    keyword_prefix: \`
    keyword_suffix: \`
    alias_prefix: \"
    alias_suffix: \"
```
Its URL is sure to be successful, here is a screenshot:

![taos](https://user-images.githubusercontent.com/20456459/97064070-1e45af00-15d6-11eb-97d3-a71798f6f5c4.png)
Or is this kind of database completely unsupported?

**Comment by scottsut** [comment]
Fixed in dev branch, will be available in next release.

**Comment by fl1906** [comment]
> @scottsut hello , 你好 TDengine is a new time series database, its JDBC URL is as follows: jdbc:TAOS://172.31.68.193:6041/testdb?user=root&password=taosdataTDengine是一个新的时序数据库，其JDBC地址如下：jdbc：TAOS：//172.31.68.193：6041/testdb？user=root&password=taosdata I configured hive2 according to your method and it was successful, but I configured TDengine and still reported the above error. This is my configuration:我按照你的方法配置了hive2，结果成功了，但是我配置了TDengine，还是报了上面的错误。这是我的配置：
> 
> ```
> TDengine:
>   name: TAOS
>   desc: TAOS
>   version:
>   driver: com.taosdata.jdbc.TSDBDriver
>   keyword_prefix: \`
>   keyword_suffix: \`
>   alias_prefix: \"
>   alias_suffix: \"
> ```
> 
> Its URL is sure to be successful, here is a screenshot:它的 URL 肯定会成功，这是截图：
> 
> ![taos](https://user-images.githubusercontent.com/20456459/97064070-1e45af00-15d6-11eb-97d3-a71798f6f5c4.png) Or is this kind of database completely unsupported?还是这种数据库完全不受支持？

你好，请问你最后是如何解决这个问题的呢，我最近也遇到了同样的问题，新版本中并没有得到解决

**Comment by fl1906** [comment]
@scottsut  你好，请问你最后是如何解决这个问题的呢，我最近也遇到了同样的问题，新版本中并没有得到解决
