### ISSUE TITLE
Davinci连接elasticsearch7.9.1报异常

### ISSUE THREAD

**Issue by zhanghucheng** [edp963/davinci#2050]
java.lang.NullPointerException: null
	at edp.core.utils.SourceUtils.getDriverClassName(SourceUtils.java:264)
	at edp.core.utils.SourceUtils.testSource(SourceUtils.java:79)
	at edp.davinci.service.impl.SourceServiceImpl.testSource(SourceServiceImpl.java:395)
	at edp.davinci.service.impl.SourceServiceImpl$$FastClassBySpringCGLIB$$88b19aec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at edp.davinci.service.impl.SourceServiceImpl$$EnhancerBySpringCGLIB$$13448cc5.testSource(<generated>)
	at edp.davinci.controller.SourceController.testSource(SourceController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by zhanghucheng** [comment]
用的多版本分离配置
elasticsearch7.9.1:
   name: elasticsearch
   desc: elasticsearch
   version: 7.9.1
   driver: org.elasticsearch.plugin.nlpcn.SqlPlug
   keyword_prefix: \`
   keyword_suffix: \`
   alias_prefix: \'
   alias_suffix: \'

**Comment by xxxllluuu** [comment]
make sure org.elasticsearch.plugin.nlpcn.SqlPlug is the right jdbc driver

**Comment by zhanghucheng** [comment]
which jdbc driver should be use

**Comment by zhanghucheng** [comment]
I try " com.facebook.presto.jdbc.PrestoDriver " and "org.elasticsearch.xpack.sql.jdbc.EsDriver" but not work

**Comment by gavin-fu** [comment]
> make sure org.elasticsearch.plugin.nlpcn.SqlPlug is the right jdbc driver

你好，目前 davinci中的可视化组件基本都使用到了子查询，但现在绝大部分 ES JDBC驱动对于子查询的支持并不完善，这是不是意味着 ES作为 davinci数据源并不合适？

**Comment by zhanghucheng** [comment]
es是可选择性 并不是唯一性 所以用它做为数据源也多了一条路挺好的

**Comment by leping** [comment]
使用es作为数据源，es版本7.12， davinci版本03.0
1、每次查询会计算count，davinci报错。
2、davici对es的某些查询报错。
在davinci新版本会修复对es的支持吗
