### ISSUE TITLE
display preview error by phantomjs doScreenshot

### ISSUE THREAD

**Issue by geosmart** [edp963/davinci#2085]
I run davinci in by docker (Alpine Linux 3.11)
init new PhantomJSDriver() throw  java.util.concurrent.TimeoutException

the detail log
```java
2020-12-11 19:35:14.853 INFO  [pool-12-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 100 lambda$null$0 - thread for screenshot start, type: display, id: 1
2020-12-11 19:35:14.854 INFO  [pool-12-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 226 generatePhantomJsDriver - Generating PhantomJs driver (/opt/visualis/visualis-run/bin/phantomjs)...
2020-12-11 19:35:14.856 INFO  [pool-12-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 150 <init> - executable: /opt/visualis/visualis-run/bin/phantomjs
2020-12-11 19:35:14.857 INFO  [pool-12-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 151 <init> - port: 23980
2020-12-11 19:35:14.857 INFO  [pool-12-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 152 <init> - arguments: [--webdriver=23980, --webdriver-logfile=/opt/visualis/visualis-run/visualis-server/phantomjsdriver.log]
2020-12-11 19:35:14.858 INFO  [pool-12-thread-5] org.openqa.selenium.phantomjs.PhantomJSDriverService 153 <init> - environment: {}
2020-12-11 19:35:34.863 ERROR [Forwarding newSession on session null to remote] org.openqa.selenium.os.OsProcess 192 checkForError - org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
2020-12-11 19:35:34.864 ERROR [pool-12-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 105 lambda$null$0 - error ScreenshotUtil.screenshot, org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: '10.199.155.84', ip: '10.199.155.84', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.11.6.el7.x86_64', java.version: '1.8.0_252'
Driver info: driver.version: PhantomJSDriver
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.phantomjs.PhantomJSCommandExecutor.execute(PhantomJSCommandExecutor.java:78) ~[phantomjsdriver-1.4.4.jar:1.4.4]
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:116) ~[phantomjsdriver-1.4.4.jar:1.4.4]
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:105) ~[phantomjsdriver-1.4.4.jar:1.4.4]
        at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:95) ~[phantomjsdriver-1.4.4.jar:1.4.4]
        at edp.davinci.service.screenshot.ScreenshotUtil.generatePhantomJsDriver(ScreenshotUtil.java:229) ~[visualis-server-0.5.0.jar:?]
        at edp.davinci.service.screenshot.ScreenshotUtil.generateWebDriver(ScreenshotUtil.java:183) ~[visualis-server-0.5.0.jar:?]
        at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:132) ~[visualis-server-0.5.0.jar:?]
        at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:102) ~[visualis-server-0.5.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_252]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:23980/status] to be available after 20002 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187) ~[selenium-remote-driver-3.9.1-.jar:?]
        ... 17 more
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:1.8.0_252]
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:148) ~[guava-23.6-jre.jar:?]
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75) ~[selenium-remote-driver-3.9.1-.jar:?]
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187) ~[selenium-remote-driver-3.9.1-.jar:?]
        ... 17 more

2020-12-11 19:35:34.866 INFO  [pool-12-thread-5] edp.davinci.service.screenshot.ScreenshotUtil 109 lambda$null$0 - thread for screenshot finish, type: display, id: 1

```

**Comment by scottsut** [comment]
Please read the **Break changes** of [0.3.0-rc release notes](https://github.com/edp963/davinci/releases/tag/v0.3.0-rc) carefully.

**Comment by geosmart** [comment]
thanks, I will try Chrome driver instead
