### ISSUE TITLE
定时任务，发送【图片作为附件的】邮件的时候报错

### ISSUE THREAD

**Issue by hexawing** [edp963/davinci#2101]
```
2020-12-29 11:15:39.228 ERROR 3724 --- [ool-70-thread-4] e.d.service.impl.CronJobServiceImpl      : File must not be null

edp.core.exception.ServerException: File must not be null
        at edp.core.utils.MailUtils.sendMail(MailUtils.java:206)
        at edp.davinci.service.impl.EmailScheduleServiceImpl.execute(EmailScheduleServiceImpl.java:181)
        at edp.davinci.service.impl.CronJobServiceImpl.lambda$executeCronJob$1(CronJobServiceImpl.java:355)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
附件为“图片”或“图片+Excel”的时候都报错，但若为“Excel”则可成功发送，所以应该不是邮件服务器的问题。

![image](https://user-images.githubusercontent.com/230037/103256249-767aa200-49c7-11eb-84ad-aea1670e9aec.png)

**Comment by xxxllluuu** [comment]
make sure the screenshot is successful, you can see the log file in /logs/user/schedule

**Comment by hexawing** [comment]
> make sure the screenshot is successful, you can see the log file in /logs/user/schedule

```
2020-12-29 17:15:53.795 --- EmailScheduleServiceImpl.java:319 : CronJob(1) workbook task:111 finish
2020-12-29 17:15:53.796 --- EmailScheduleServiceImpl.java:319 : CronJob(1) workbook task:大屏 finish
2020-12-29 17:15:53.798 --- EmailScheduleServiceImpl.java:330 : CronJob(1) fetched excel contents, count:2
2020-12-29 17:15:53.807 --- EmailScheduleServiceImpl.java:164 : CronJob(1) is ready to send email
2020-12-29 17:15:54.338 --- CronJobServiceImpl.java:358 : File must not be null
2020-12-29 17:16:00.027 --- QuartzHandler.java:124 : ScheduleJob (:CRONJOB_1) not found
```

File must not be null

**Comment by scottsut** [comment]
请提供：
1. 完整错误日志.
2. `application.yml` 中的 `server` 和 `screenshot` 配置.
3. Chrome 版本以及 chromedriver 版本.

**Comment by hexawing** [comment]
> 请提供：
> 
> 1. 完整错误日志.
> 2. `application.yml` 中的 `server` 和 `screenshot` 配置.
> 3. Chrome 版本以及 chromedriver 版本.

1.完整日志如下：
```
2020-12-30 11:27:48.641 --- ExecutorUtil.java:73 : Cronjob_Executor keep alive time:0, poolSize:0, waiting queue size:0, task count:0, completed task size:0
2020-12-30 11:27:48.681 --- EmailScheduleServiceImpl.java:124 : CronJob(1) is start! --------------
2020-12-30 11:27:48.701 --- BaseScheduleService.java:72 : CronJob(1) fetching images contents
2020-12-30 11:27:49.724 --- ScreenshotUtil.java:90 : Start screenshot for job(1)
2020-12-30 11:27:49.732 --- ScreenshotUtil.java:96 : Cronjob(1) thread(1) for screenshot start, type:display, id:1, total:2
2020-12-30 11:27:49.733 --- ScreenshotUtil.java:214 : user RemoteWebDriver ($your_remote_webdriver_url$)
2020-12-30 11:27:49.745 --- ScreenshotUtil.java:218 : java.net.MalformedURLException: no protocol: $your_remote_webdriver_url$

java.net.MalformedURLException: no protocol: $your_remote_webdriver_url$
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateChromeDriver(ScreenshotUtil.java:216)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateWebDriver(ScreenshotUtil.java:193)
	at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:127)
	at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2020-12-30 11:27:49.767 --- ScreenshotUtil.java:101 : Cronjob(1) thread(1) screenshot error
2020-12-30 11:27:49.767 --- ScreenshotUtil.java:102 : The driver executable is a directory: c:\downloads

java.lang.IllegalStateException: The driver executable is a directory: c:\downloads
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:138)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:131)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateChromeDriver(ScreenshotUtil.java:242)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateWebDriver(ScreenshotUtil.java:193)
	at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:127)
	at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2020-12-30 11:27:49.768 --- ScreenshotUtil.java:104 : Cronjob(1) thread(1) for screenshot finish, type:display, id:1, total:2
2020-12-30 11:27:49.764 --- ScreenshotUtil.java:96 : Cronjob(1) thread(1) for screenshot start, type:DASHBOARD, id:1, total:2
2020-12-30 11:27:49.768 --- ScreenshotUtil.java:214 : user RemoteWebDriver ($your_remote_webdriver_url$)
2020-12-30 11:27:49.769 --- ScreenshotUtil.java:218 : java.net.MalformedURLException: no protocol: $your_remote_webdriver_url$

java.net.MalformedURLException: no protocol: $your_remote_webdriver_url$
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateChromeDriver(ScreenshotUtil.java:216)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateWebDriver(ScreenshotUtil.java:193)
	at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:127)
	at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2020-12-30 11:27:49.771 --- ScreenshotUtil.java:101 : Cronjob(1) thread(2) screenshot error
2020-12-30 11:27:49.771 --- ScreenshotUtil.java:102 : The driver executable is a directory: c:\downloads

java.lang.IllegalStateException: The driver executable is a directory: c:\downloads
	at com.google.common.base.Preconditions.checkState(Preconditions.java:585)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:138)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:131)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:32)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:137)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:339)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:88)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateChromeDriver(ScreenshotUtil.java:242)
	at edp.davinci.service.screenshot.ScreenshotUtil.generateWebDriver(ScreenshotUtil.java:193)
	at edp.davinci.service.screenshot.ScreenshotUtil.doScreenshot(ScreenshotUtil.java:127)
	at edp.davinci.service.screenshot.ScreenshotUtil.lambda$null$0(ScreenshotUtil.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2020-12-30 11:27:49.771 --- ScreenshotUtil.java:104 : Cronjob(1) thread(2) for screenshot finish, type:DASHBOARD, id:1, total:2
2020-12-30 11:27:49.775 --- ScreenshotUtil.java:122 : Cronjob(1) finish screenshot
2020-12-30 11:27:49.775 --- BaseScheduleService.java:124 : CronJob(1) fetched images contents, count:2
2020-12-30 11:27:49.775 --- EmailScheduleServiceImpl.java:194 : CronJob(1) fetching excel contents
2020-12-30 11:27:54.782 --- EmailScheduleServiceImpl.java:302 : CronJob(1) submit workbook task:111, thread:1, total:2
2020-12-30 11:27:54.786 --- ExecutorUtil.java:73 : WORKBOOK_WORKERS keep alive time:0, poolSize:0, waiting queue size:0, task count:0, completed task size:0
2020-12-30 11:27:54.796 --- EmailScheduleServiceImpl.java:302 : CronJob(1) submit workbook task:大屏, thread:2, total:2
2020-12-30 11:27:54.796 --- ExecutorUtil.java:73 : WORKBOOK_WORKERS keep alive time:0, poolSize:1, waiting queue size:0, task count:1, completed task size:0
2020-12-30 11:27:54.807 --- WorkbookWorker.java:73 : Task(Schedule_1) workbook worker start action=MAIL, xid=null
2020-12-30 11:27:54.812 --- WorkbookWorker.java:73 : Task(Schedule_1) workbook worker start action=MAIL, xid=null
2020-12-30 11:27:56.935 --- ExecutorUtil.java:73 : SHEET_WORKERS keep alive time:0, poolSize:0, waiting queue size:0, task count:0, completed task size:0
2020-12-30 11:27:56.936 --- ExecutorUtil.java:73 : SHEET_WORKERS keep alive time:0, poolSize:0, waiting queue size:0, task count:0, completed task size:0
2020-12-30 11:27:56.958 --- ExecutorUtil.java:73 : SHEET_WORKERS keep alive time:0, poolSize:2, waiting queue size:0, task count:2, completed task size:0
2020-12-30 11:27:56.964 --- ExecutorUtil.java:73 : SHEET_WORKERS keep alive time:0, poolSize:3, waiting queue size:0, task count:3, completed task size:0
2020-12-30 11:27:57.340 --- SheetWorker.java:91 : Task(Schedule_1) sheet worker(name:报价测试, sheetNo:1, sheetName:1-报价测试) query start sql:SELECT `DATE_FORMAT(quotes.created_at, '%Y-%m')`, `name`, COUNT(`id`) AS 'count(id)'
FROM (
	SELECT quotes.id, quotes.`number`, quotes.cny, bevies.name
		, year(quotes.created_at)
		, DATE_FORMAT(quotes.created_at, '%Y-%m')
	FROM quotes
		LEFT JOIN bevies ON quotes.processor_bevy_id = bevies.id
	WHERE quotes.created_at BETWEEN '2020-01-01' AND '2021-01-01'
) T
WHERE `name` != '""'
GROUP BY `DATE_FORMAT(quotes.created_at, '%Y-%m')`, `name`, md5:8430CB837CE7BAD9
2020-12-30 11:27:57.421 --- SheetWorker.java:109 : Task(Schedule_1) sheet worker(name:报价测试, sheetNo:1, sheetName:1-报价测试) query finish md5:8430CB837CE7BAD9, count:50
2020-12-30 11:27:57.501 --- SheetWorker.java:91 : Task(Schedule_1) sheet worker(name:桑基图, sheetNo:3, sheetName:3-桑基图) query start sql:SELECT `signer`, `contract type`, SUM(`cny`) AS 'sum(cny)'
FROM (
	SELECT contracts.id AS "`contract id`", contracts.`number`, contracts.customer_number, contracts.summary, contracts.signer_user_id
		, contracts.dealer_user_id, contracts.signer_bevy_id, contracts.processor_bevy_id, contracts.customer_unit_id, contracts.end_user_customer_id
		, contracts.buyer_customer_id, contracts.business_unit_id, contracts.business_contact_id, contracts.channel_unit_id, contracts.cover_unit_id
		, contracts.our_company_id, contracts.requirement_id, contracts.currency_id, contracts.state, contracts.`sum`
		, contracts.exchange_rate, contracts.cny, contracts.pay_mode_id, contracts.does_need_install, contracts.does_need_lc
		, contracts.receive_lc_at, contracts.lc_number, contracts.invoice, contracts.profit, contracts.estimate_profit
		, contracts.total_collection, contracts.total_invoiced, contracts.`comment`, contracts.quote_id, contracts.salelog_id
		, contracts.contract_type, contracts.group_id, contracts.formation_id, contracts.signed_at, contracts.invoiced_at
		, contracts.business_comment, contracts.is_auto_update, contracts.is_auto_acceptance, contracts.is_pay_mode_franchised, contracts.is_profit_franchised
		, contracts.credit_flag, contracts.receivable_comment, contracts.created_at, contracts.updated_at, contracts.contractable_id
		, contracts.contractable_type, bevies.id AS "`bevy id`", bevies.`name` AS `signer`, bevies.`number` AS "`bevy number`", bevies.description
		, bevies.superior, bevies.is_frozen, bevies.is_entity, bevies.is_project, bevies.is_collaboration
		, bevies.created_at AS "`bevy created`", d1.display AS "`contract type`"
	FROM contracts
		LEFT JOIN bevies ON bevies.id = contracts.signer_bevy_id
		LEFT JOIN dictionaries d1
		ON d1.data_type = 'contract_type'
			AND d1.value = contracts.contract_type
	WHERE contracts.created_at > '2020-01-01'
) T
GROUP BY `signer`, `contract type`, md5:CC71DCC2597BBF2F
2020-12-30 11:27:57.509 --- SheetWorker.java:91 : Task(Schedule_1) sheet worker(name:一个饼图, sheetNo:1, sheetName:1-一个饼图) query start sql:SELECT `signer`, SUM(`cny`) AS 'sum(cny)'
FROM (
	SELECT contracts.id AS "`contract id`", contracts.`number`, contracts.customer_number, contracts.summary, contracts.signer_user_id
		, contracts.dealer_user_id, contracts.signer_bevy_id, contracts.processor_bevy_id, contracts.customer_unit_id, contracts.end_user_customer_id
		, contracts.buyer_customer_id, contracts.business_unit_id, contracts.business_contact_id, contracts.channel_unit_id, contracts.cover_unit_id
		, contracts.our_company_id, contracts.requirement_id, contracts.currency_id, contracts.state, contracts.`sum`
		, contracts.exchange_rate, contracts.cny, contracts.pay_mode_id, contracts.does_need_install, contracts.does_need_lc
		, contracts.receive_lc_at, contracts.lc_number, contracts.invoice, contracts.profit, contracts.estimate_profit
		, contracts.total_collection, contracts.total_invoiced, contracts.`comment`, contracts.quote_id, contracts.salelog_id
		, contracts.contract_type, contracts.group_id, contracts.formation_id, contracts.signed_at, contracts.invoiced_at
		, contracts.business_comment, contracts.is_auto_update, contracts.is_auto_acceptance, contracts.is_pay_mode_franchised, contracts.is_profit_franchised
		, contracts.credit_flag, contracts.receivable_comment, contracts.created_at, contracts.updated_at, contracts.contractable_id
		, contracts.contractable_type, bevies.id AS "`bevy id`", bevies.`name` AS `signer`, bevies.`number` AS "`bevy number`", bevies.description
		, bevies.superior, bevies.is_frozen, bevies.is_entity, bevies.is_project, bevies.is_collaboration
		, bevies.created_at AS "`bevy created`", d1.display AS "`contract type`"
	FROM contracts
		LEFT JOIN bevies ON bevies.id = contracts.signer_bevy_id
		LEFT JOIN dictionaries d1
		ON d1.data_type = 'contract_type'
			AND d1.value = contracts.contract_type
	WHERE contracts.created_at > '2020-01-01'
) T
GROUP BY `signer`, md5:069B132248B219C0
2020-12-30 11:27:57.645 --- SheetWorker.java:91 : Task(Schedule_1) sheet worker(name:一个饼图, sheetNo:2, sheetName:2-一个饼图) query start sql:SELECT `signer`, SUM(`cny`) AS 'sum(cny)'
FROM (
	SELECT contracts.id AS "`contract id`", contracts.`number`, contracts.customer_number, contracts.summary, contracts.signer_user_id
		, contracts.dealer_user_id, contracts.signer_bevy_id, contracts.processor_bevy_id, contracts.customer_unit_id, contracts.end_user_customer_id
		, contracts.buyer_customer_id, contracts.business_unit_id, contracts.business_contact_id, contracts.channel_unit_id, contracts.cover_unit_id
		, contracts.our_company_id, contracts.requirement_id, contracts.currency_id, contracts.state, contracts.`sum`
		, contracts.exchange_rate, contracts.cny, contracts.pay_mode_id, contracts.does_need_install, contracts.does_need_lc
		, contracts.receive_lc_at, contracts.lc_number, contracts.invoice, contracts.profit, contracts.estimate_profit
		, contracts.total_collection, contracts.total_invoiced, contracts.`comment`, contracts.quote_id, contracts.salelog_id
		, contracts.contract_type, contracts.group_id, contracts.formation_id, contracts.signed_at, contracts.invoiced_at
		, contracts.business_comment, contracts.is_auto_update, contracts.is_auto_acceptance, contracts.is_pay_mode_franchised, contracts.is_profit_franchised
		, contracts.credit_flag, contracts.receivable_comment, contracts.created_at, contracts.updated_at, contracts.contractable_id
		, contracts.contractable_type, bevies.id AS "`bevy id`", bevies.`name` AS `signer`, bevies.`number` AS "`bevy number`", bevies.description
		, bevies.superior, bevies.is_frozen, bevies.is_entity, bevies.is_project, bevies.is_collaboration
		, bevies.created_at AS "`bevy created`", d1.display AS "`contract type`"
	FROM contracts
		LEFT JOIN bevies ON bevies.id = contracts.signer_bevy_id
		LEFT JOIN dictionaries d1
		ON d1.data_type = 'contract_type'
			AND d1.value = contracts.contract_type
	WHERE contracts.created_at > '2020-01-01'
) T
GROUP BY `signer`, md5:069B132248B219C0
2020-12-30 11:27:57.873 --- SheetWorker.java:109 : Task(Schedule_1) sheet worker(name:桑基图, sheetNo:3, sheetName:3-桑基图) query finish md5:CC71DCC2597BBF2F, count:37
2020-12-30 11:27:57.874 --- SheetWorker.java:109 : Task(Schedule_1) sheet worker(name:一个饼图, sheetNo:1, sheetName:1-一个饼图) query finish md5:069B132248B219C0, count:17
2020-12-30 11:27:58.064 --- SheetWorker.java:109 : Task(Schedule_1) sheet worker(name:一个饼图, sheetNo:2, sheetName:2-一个饼图) query finish md5:069B132248B219C0, count:17
2020-12-30 11:27:58.246 --- SheetWorker.java:133 : Task(Schedule_1) sheet worker(一个饼图) complete md5=069B132248B219C0, status=true, action=MAIL, xid=null, xUUID=24997e1d48054829b30cacda0fd3ebf0, sheetNo=1, sheetName=1-一个饼图, dashboardId=null, widgetId=1, cost=1280ms
2020-12-30 11:27:58.262 --- SheetWorker.java:133 : Task(Schedule_1) sheet worker(一个饼图) complete md5=069B132248B219C0, status=true, action=MAIL, xid=null, xUUID=24997e1d48054829b30cacda0fd3ebf0, sheetNo=2, sheetName=2-一个饼图, dashboardId=null, widgetId=1, cost=1296ms
2020-12-30 11:27:58.608 --- SheetWorker.java:133 : Task(Schedule_1) sheet worker(桑基图) complete md5=CC71DCC2597BBF2F, status=true, action=MAIL, xid=null, xUUID=24997e1d48054829b30cacda0fd3ebf0, sheetNo=3, sheetName=3-桑基图, dashboardId=null, widgetId=2, cost=1642ms
2020-12-30 11:27:58.699 --- SheetWorker.java:133 : Task(Schedule_1) sheet worker(报价测试) complete md5=8430CB837CE7BAD9, status=true, action=MAIL, xid=null, xUUID=6c8186a0869947658ac426a829db6a75, sheetNo=1, sheetName=1-报价测试, dashboardId=null, widgetId=3, cost=1761ms
2020-12-30 11:27:58.849 --- WorkbookWorker.java:179 : Task(Schedule_1) workbook worker complete status=true, action=MAIL, xUUID=6c8186a0869947658ac426a829db6a75, filePath=c:\davinci\userfiles\email\20201230\excel\6c8186a0869947658ac426a829db6a75_1609298878700.xlsx, cost=4042ms
2020-12-30 11:27:58.850 --- EmailScheduleServiceImpl.java:319 : CronJob(1) workbook task:111 finish
2020-12-30 11:27:58.853 --- WorkbookWorker.java:179 : Task(Schedule_1) workbook worker complete status=true, action=MAIL, xUUID=24997e1d48054829b30cacda0fd3ebf0, filePath=c:\davinci\userfiles\email\20201230\excel\24997e1d48054829b30cacda0fd3ebf0_1609298878613.xlsx, cost=4041ms
2020-12-30 11:27:58.854 --- EmailScheduleServiceImpl.java:319 : CronJob(1) workbook task:大屏 finish
2020-12-30 11:27:58.855 --- EmailScheduleServiceImpl.java:330 : CronJob(1) fetched excel contents, count:2
2020-12-30 11:27:58.857 --- EmailScheduleServiceImpl.java:164 : CronJob(1) is ready to send email
2020-12-30 11:27:59.574 --- CronJobServiceImpl.java:358 : File must not be null
```

2. server配置如下：
```
server:
  protocol: http
  address: 172.18.10.15
  port: 8080

  servlet:
    context-path: /

  # Used for mail and download services, can be empty, careful configuration
  # By default, 'server.address' and 'server.port' is used as the string value.
  # access:
  #  address:
  #  port:


## jwt is one of the important configuration of the application
## jwt config cannot be null or empty
jwtToken:
  secret: secret
  timeout: 1800000
  algorithm: HS512
```
screenshot配置如下：
```
screenshot:
  default_browser: CHROME
  timeout_second: 600
  chromedriver_path: c:\downloads
  remote_webdriver_url: $your_remote_webdriver_url$
```
我知道肯定是`$your_remote_webdriver_url$`这里不对，但我不知道怎么写……

3. Chrome版本是
`版本 87.0.4280.88（正式版本） （64 位）`
chromedriver是下载的这个对应的版本，单独运行后显示：
```
Starting ChromeDriver 87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

谢谢！

**Comment by scottsut** [comment]
如果你的 chromedriver 可执行文件在 `c:\downloads` 下，`chromedriver_path` 就写成 `c:\downloads\chromedriver`，windows 环境加上 exe 后缀名。

**Comment by hexawing** [comment]
> 如果你的 chromedriver 可执行文件在 `c:\downloads` 下，`chromedriver_path` 就写成 `c:\downloads\chromedriver`，windows 环境加上 exe 后缀名。

那么`remote_webdriver_url`呢？

**Comment by scottsut** [comment]
可以不用管

**Comment by hexawing** [comment]
> 可以不用管

可以了！谢谢！！！
