### ISSUE TITLE
Not supported data type

### ISSUE THREAD

**Issue by fangunun** [edp963/davinci#2249]
After adding a new data source, the page test connection is successful. Click Save and an error is reported:

edp.core.exception.SourceException: Not supported data type: jdbcUrl=jdbc:TAOS://td01:6030/zjy
	at edp.core.utils.SourceUtils.isSupportedDatasource(SourceUtils.java:210)
	at edp.core.utils.SqlUtils$SqlUtilsBuilder.build(SqlUtils.java:1021)
	at edp.core.utils.SqlUtils.init(SqlUtils.java:127)
	at edp.core.utils.SqlUtils$$FastClassBySpringCGLIB$$33c0f0b2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at edp.core.utils.SqlUtils$$EnhancerBySpringCGLIB$$c3950fb2.init(<generated>)
	at edp.davinci.service.impl.SourceServiceImpl.testConnection(SourceServiceImpl.java:246)
	at edp.davinci.service.impl.SourceServiceImpl.createSource(SourceServiceImpl.java:207)
	at edp.davinci.service.impl.SourceServiceImpl$$FastClassBySpringCGLIB$$88b19aec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at edp.davinci.service.impl.SourceServiceImpl$$EnhancerBySpringCGLIB$$6e7f3474.createSource(<generated>)
	at edp.davinci.controller.SourceController.createSource(SourceController.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by fl1906** [comment]
@fangunun 你好，请问你最后是如何解决这个问题的呢，我最近也遇到了同样的问题，新版本中并没有得到解决
