### ISSUE TITLE
Error reporting when using Jdb to connect to Hive for report development

### ISSUE THREAD

**Issue by sq8852161** [edp963/davinci#861]
The table of hive can be queried normally in the view.：
![view1bug](https://user-images.githubusercontent.com/9211058/57514332-d29c3880-7342-11e9-9175-797e01185b7d.PNG)

On widget create
![widget1bug](https://user-images.githubusercontent.com/9211058/57514534-4dfdea00-7343-11e9-8a4d-2d213f63caa1.PNG)
以下语句由报表系统生成，但是在Hive中无法执行，报Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
错误。
SELECT
 tt
,
 sum(v1) AS `sum(v1)`
FROM (select  time as tt,v1,amount from carddata.datalist) T
GROUP BY tt

2019-05-10 16:46:08.215 ERROR 17256 --- [0.1-8080-exec-1] edp.core.utils.SqlUtils                  : StatementCallback; uncategorized SQLException for SQL [SELECT
 tt
,
 sum(v1) AS `sum(v1)`
FROM (select  time as tt,v1,amount from carddata.datalist) T
GROUP BY tt
]; SQL state [HY000]; error code [500051]; [Cloudera][HiveJDBCDriver](500051) ERROR processing query/statement. Error Code: 2, SQL state: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask, Query: SELECT `T`.`tt`, SUM(`T`.`v1`) `sum(v1)` FROM (SELECT `carddata_datalist`.`time` `tt`, `carddata_datalist`.`v1`, `carddata_datalist`.`amount` FROM `carddata`.`datalist` `carddata_datalist`) `T` GROUP BY `T`.`tt`.; nested exception is java.sql.SQLException: [Cloudera][HiveJDBCDriver](500051) ERROR processing query/statement. Error Code: 2, SQL state: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask, Query: SELECT `T`.`tt`, SUM(`T`.`v1`) `sum(v1)` FROM (SELECT `carddata_datalist`.`time` `tt`, `carddata_datalist`.`v1`, `carddata_datalist`.`amount` FROM `carddata`.`datalist` `carddata_datalist`) `T` GROUP BY `T`.`tt`.
edp.core.exception.ServerException: StatementCallback; uncategorized SQLException for SQL [SELECT
 tt
,
 sum(v1) AS `sum(v1)`
FROM (select  time as tt,v1,amount from carddata.datalist) T
GROUP BY tt
]; SQL state [HY000]; error code [500051]; [Cloudera][HiveJDBCDriver](500051) ERROR processing query/statement. Error Code: 2, SQL state: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask, Query: SELECT `T`.`tt`, SUM(`T`.`v1`) `sum(v1)` FROM (SELECT `carddata_datalist`.`time` `tt`, `carddata_datalist`.`v1`, `carddata_datalist`.`amount` FROM `carddata`.`datalist` `carddata_datalist`) `T` GROUP BY `T`.`tt`.; nested exception is java.sql.SQLException: [Cloudera][HiveJDBCDriver](500051) ERROR processing query/statement. Error Code: 2, SQL state: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask, Query: SELECT `T`.`tt`, SUM(`T`.`v1`) `sum(v1)` FROM (SELECT `carddata_datalist`.`time` `tt`, `carddata_datalist`.`v1`, `carddata_datalist`.`amount` FROM `carddata`.`datalist` `carddata_datalist`) `T` GROUP BY `T`.`tt`.
	at edp.core.utils.SqlUtils.query4Paginate(SqlUtils.java:236)
	at edp.core.utils.SqlUtils.syncQuery4Paginate(SqlUtils.java:304)
	at edp.davinci.service.impl.ViewServiceImpl.getResultDataList(ViewServiceImpl.java:611)
	at edp.davinci.service.impl.ViewServiceImpl.getData(ViewServiceImpl.java:504)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
	at com.sun.proxy.$Proxy107.getData(Unknown Source)
	at edp.davinci.controller.ViewController.getData(ViewController.java:308)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-05-10 16:46:08.217  INFO 17256 --- [0.1-8080-exec-1] edp.davinci.controller.ViewController    : request getData for: >> 31536ms

**Comment by scottsut** [comment]
Properties `alias_prefix` and `alias_suffix` need to be added in [datasource config](https://edp963.github.io/davinci/deployment.html#3-%E6%95%B0%E6%8D%AE%E6%BA%90%E9%85%8D%E7%BD%AE)
